spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/casebefrank
    username: root
    password: password
    jpa:
      dhibernate.ddl-auto: update
      dhibernate.format_sql: true
      generate-ddl: true
      show-sql: true


