spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/casebefrank
    username: root
    password: password
    jpa:
      dhibernate.ddl-auto: update
      dhibernate.format_sql: true
      generate-ddl: true
      show-sql: true

#  /^([1-2]{1}[0-9]{3})([0-1]{1}[0-2]{1})([0-3]{1}[\d]{1})-([\d]{5})$/i

#  function validateEmail(email) {
#  var regex = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
#  return regex.test(email);
#}

